SET search_path TO minha_game_list;

INSERT INTO generos (Nome) VALUES
('Ação'),
('Aventura'),
('RPG'),
('JRPG'),
('MMORPG'),
('Estratégia'),
('Estratégia em Tempo Real'),
('Estratégia por Turno'),
('Tático'),
('FPS'),
('TPS'),
('Stealth'),
('Terror'),
('Terror Psicológico'),
('Survival Horror'),
('Survival'),
('Hack and Slash'),
('Beat ’em up'),
('Roguelike'),
('Roguelite'),
('Metroidvania'),
('Plataforma'),
('Corrida'),
('Simulação'),
('Simulador de Vida'),
('Simulador de Fazenda'),
('Simulador de Voo'),
('Esportes'),
('Futebol'),
('Basquete'),
('Luta'),
('MOBA'),
('Battle Royale'),
('Sandbox'),
('Mundo Aberto'),
('Exploração'),
('Construção'),
('Crafting'),
('Puzzle'),
('Cardgame'),
('Deckbuilder'),
('Tower Defense'),
('Autochess'),
('Musical'),
('Ritmo'),
('Cooperativo'),
('Multiplayer Local'),
('Online'),
('PvP'),
('PvE'),
('Narrativo'),
('Visual Novel'),
('Dating Sim'),
('Indie'),
('AAA'),
('Soulslike'),
('Bullet Hell'),
('Bullet Heaven'),
('Investigação'),
('Mistério'),
('Crime'),
('Fantasia'),
('Alta Fantasia'),
('Baixa Fantasia'),
('Sci-Fi'),
('Cyberpunk'),
('Steampunk'),
('Pós-Apocalipse'),
('Zumbis'),
('Espacial'),
('Histórico'),
('Infantil'),
('Educacional'),
('Humor'),
('Satírico'),
('Retro'),
('Pixel Art'),
('Voxel'),
('Low Poly'),
('Realista'),
('3D'),
('2D'),
('2.5D'),
('Top-down'),
('Isométrico'),
('Primeira Pessoa'),
('Terceira Pessoa'),
('Side-scroller'),
('Tycoon'),
('Economia'),
('Gerenciamento de Tempo'),
('Administração'),
('Vida Cotidiana'),
('Slice of Life'),
('Gacha'),
('Loot-based'),
('Escolhas Importam'),
('Text Adventure');
